// usbdisplay - Pico 2 (W) firmware
//
//   USB CDC serial  ->  text terminal (term.c)  ->  1bpp scanline  ->  TMDS  ->  DVI
//
// Core 1 renders: for every scanline it blits font rows for the 80 characters
// of that text row into a 1-bit-per-pixel line buffer and TMDS-encodes it
// (tmds_encode_1bpp). No full framebuffer is stored: the whole screen costs
// 80x30 = 2400 bytes of RAM (8x16 font), and the DVI output is a true 1bpp
// 640x480p60 image that the Waveshare panel upscales to 1024x600.
// Core 0 receives bytes from USB and feeds the terminal.

#include <stdio.h>
#include <string.h>
#include "pico/stdlib.h"
#include "pico/multicore.h"
#include "pico/sem.h"
#include "pico/stdio_usb.h"
#include "hardware/clocks.h"
#include "hardware/vreg.h"
#include "hardware/structs/bus_ctrl.h"

#include "dvi.h"
#include "dvi_serialiser.h"
#include "tmds_encode.h"

#include "dvi_pins.h"
#include "led.h"
#ifdef GFX
#include "gfx_dec.h"
#ifdef USE_PSRAM
#include "psram.h"
#endif
#ifdef GFX_UART
#include "uart_lane.h"
#endif
#endif

// Font: 8-pixel-wide glyphs for ASCII 32..126 laid out as font[row * 95 + (ch - 32)],
// bit 0 = leftmost pixel. Picked at build time by CMake (-DFONT=...):
//   dejavu     (default) DejaVu Sans Mono hinted to 8x16, the usual Debian terminal font
//   terminus   Terminus 8x16, a crisp pixel font
//   legacy8x8  PicoDVI's 8x8 font (doubled vertically by default)
// The 8x16 tables are generated by tools/make_font.py.
#if defined(FONT_LEGACY_8X8)
#include "font_8x8.h"
#define FONT_TABLE        font_8x8
#define FONT_CHAR_HEIGHT  8
#elif defined(FONT_TERMINUS)
#include "font_8x16_terminus.h"
#define FONT_TABLE        font_8x16_terminus
#define FONT_CHAR_HEIGHT  16
#else
#include "font_8x16_dejavu.h"
#define FONT_TABLE        font_8x16_dejavu
#define FONT_CHAR_HEIGHT  16
#endif
#define FONT_CHAR_WIDTH   8
#define FONT_N_CHARS      95
#define FONT_FIRST_ASCII  32

// 640x480p60: the mode Waveshare's own demo uses for this panel.
#define FRAME_WIDTH   640
#define FRAME_HEIGHT  480
#define VREG_VSEL     VREG_VOLTAGE_1_20
#define DVI_TIMING    dvi_timing_640x480p_60hz

// Vertical pixel repeat per font row (CMake picks the default: 1 for the 8x16
// fonts -> 80x30 characters; 2 for legacy8x8 -> 8x16 cells, also 80x30;
// legacy8x8 with 1 gives 80x60 characters).
#ifndef FONT_SCALE_Y
#define FONT_SCALE_Y 1
#endif
// 1 = black text on white
#ifndef INVERT_VIDEO
#define INVERT_VIDEO 0
#endif

#define CELL_H     (FONT_CHAR_HEIGHT * FONT_SCALE_Y)
// The cursor is an underline over the last CURSOR_LINES scanlines of its cell.
#define CURSOR_LINES 2

// TERM_COLS / TERM_ROWS are passed by CMake so term.c and main.c agree.
#include "term.h"
_Static_assert(TERM_COLS == FRAME_WIDTH / FONT_CHAR_WIDTH, "TERM_COLS mismatch");
_Static_assert(TERM_ROWS == FRAME_HEIGHT / CELL_H, "TERM_ROWS mismatch (FONT_SCALE_Y)");

static struct dvi_inst dvi0;
static struct semaphore dvi_start_sem;
static term_t term;
static volatile bool dvi_running;   // set by core 1 once DVI output has started

#ifdef GFX
// Graphics mode (build with  cmake .. -DGFX=ON): a 640x480 RGB332 framebuffer (307 KB) filled by the
// tile-op decoder in gfx_dec.c. In this build the DVI output is full colour, and the text terminal is
// expanded to 8 bit pixels (white on black) so both modes go through the same encoder.
#define GFX_W FRAME_WIDTH
#define GFX_H FRAME_HEIGHT
#ifndef GFX_CACHE_TILES
#define GFX_CACHE_TILES 256          // tiles in the tile cache: in PSRAM when USE_PSRAM and it works, else in SRAM
#endif
#ifndef GFX_SRAM_TILES
#define GFX_SRAM_TILES GFX_CACHE_TILES   // size of the SRAM cache (the fallback when there is no working PSRAM)
#endif
#define GFX_RAW_MAX 16384
#define GFX_L1_RAW 8192              // largest packet accepted on the UART link
#define GFX_BM_BYTES (1024u * 1024u) // bitmap memory carved out of the PSRAM
#define GFX_SRAM_ALLOC (GFX_SRAM_TILES > 0 ? GFX_SRAM_TILES : 1)
static uint8_t gfx_fb[GFX_W * GFX_H] __attribute__((aligned(4)));
static uint8_t gfx_cache_sram[GFX_SRAM_ALLOC * GFX_TILE_BYTES];
static uint8_t gfx_payload[GFX_RAW_MAX + 2];
static uint8_t gfx_raw[GFX_RAW_MAX];
#ifdef GFX_UART
static uint8_t gfx_payload1[GFX_L1_RAW + 2];
static uint32_t uart_baud;
#endif
static size_t psram_bytes;           // 0 = none / failed self-test
static int gfx_cache_tiles;          // what is actually in use
static uint32_t gfx_bm_bytes;
static gfx_dec_t gfx;
static volatile bool gfx_active;
static uint64_t expand_lut[256];                            // 1bpp font byte -> 8 pixels of 0x00 / 0xFF
static uint64_t line8[FRAME_WIDTH / 8];                      // one text-mode scanline as 8 bit pixels

static void __not_in_flash_func(encode_line8)(const uint32_t *px) {
	uint32_t *tmdsbuf;
	queue_remove_blocking(&dvi0.q_tmds_free, &tmdsbuf);
	const uint pw = FRAME_WIDTH / DVI_SYMBOLS_PER_WORD;
	// RGB332: bits 7:5 red, 4:2 green, 1:0 blue. TMDS channel 0 = blue, 1 = green, 2 = red.
	tmds_encode_data_channel_8bpp(px, tmdsbuf + 0 * pw, FRAME_WIDTH, 1, 0);
	tmds_encode_data_channel_8bpp(px, tmdsbuf + 1 * pw, FRAME_WIDTH, 4, 2);
	tmds_encode_data_channel_8bpp(px, tmdsbuf + 2 * pw, FRAME_WIDTH, 7, 5);
	queue_add_blocking(&dvi0.q_tmds_valid, &tmdsbuf);
}
#endif

static void __not_in_flash_func(prepare_scanline)(uint y) {
#ifdef GFX
	if (gfx_active) {
		encode_line8((const uint32_t *)&gfx_fb[(size_t)y * GFX_W]);
		return;
	}
#endif
	static uint32_t scanbuf32[FRAME_WIDTH / 32];
	uint8_t *scanbuf = (uint8_t *)scanbuf32;

	uint r = y / CELL_H;
	uint fy = (y % CELL_H) / FONT_SCALE_Y;
	const char *row = term_row(&term, r);
	const uint8_t *font = (const uint8_t *)FONT_TABLE + fy * FONT_N_CHARS;

	for (uint i = 0; i < TERM_COLS; ++i) {
		uint8_t b = font[(uint8_t)row[i] - FONT_FIRST_ASCII];
#if INVERT_VIDEO
		b = ~b;
#endif
		scanbuf[i] = b;
	}
	// Underline cursor (inverts the pixels, so it shows over text too).
	if (r == term.row && (y % CELL_H) >= CELL_H - CURSOR_LINES) {
		uint c = term.col;
		if (c < TERM_COLS) scanbuf[c] ^= 0xFF;
	}

#ifdef GFX
	for (uint i = 0; i < FRAME_WIDTH / 8; ++i) line8[i] = expand_lut[scanbuf[i]];   // text mode: 1bpp -> 8bpp
	encode_line8((const uint32_t *)line8);
#else
	uint32_t *tmdsbuf;
	queue_remove_blocking(&dvi0.q_tmds_free, &tmdsbuf);
	tmds_encode_1bpp(scanbuf32, tmdsbuf, FRAME_WIDTH);
	queue_add_blocking(&dvi0.q_tmds_valid, &tmdsbuf);
#endif
}

static void __not_in_flash_func(core1_scanline_callback)(void) {
	static uint y = 1;
	prepare_scanline(y);
	y = (y + 1) % FRAME_HEIGHT;
}

static void __not_in_flash_func(core1_main)(void) {
	dvi_register_irqs_this_core(&dvi0, DMA_IRQ_0);
	sem_acquire_blocking(&dvi_start_sem);
	dvi_start(&dvi0);
	dvi_running = true;
	// Scanline rendering is entirely IRQ driven.
	while (1) __wfi();
}

static void term_puts(const char *s) {
	while (*s) term_feed(&term, (uint8_t)*s++);
}

// LED status (see README):
//   solid on                 starting up / hung before DVI started
//   3 quick blinks           DVI output started
//   fast blink (5 Hz)        ERROR: DVI did not start
//   slow blink (1 Hz)        running, no USB host connected (or host has DTR low)
//   short flash every 2 s    running, USB host connected, idle
//   solid on                 receiving data right now
static bool led_pattern(uint64_t now_us, bool error, bool host, uint64_t last_rx_us) {
	if (error) return (now_us / 100000) & 1;
	if (last_rx_us && now_us - last_rx_us < 40000) return true;
	if (!host) return (now_us / 500000) & 1;
	return (now_us % 2000000) < 100000;
}

#ifdef GFX
// Graphics mode input: USB bytes are collected into a small stage, UART bytes are read straight from the DMA ring.
// Either link may be told to wait (gfx_dec holds a packet that arrived before its predecessor), in which case its
// bytes stay where they are until the other link has delivered.
static uint8_t usb_stage[256];
static size_t usb_len, usb_off;

static bool gfx_poll(void) {
	bool did = false;
	if (usb_off >= usb_len && !gfx_dec_lane_blocked(&gfx, 0)) {
		usb_len = usb_off = 0;
		int c;
		while (usb_len < sizeof usb_stage && (c = getchar_timeout_us(0)) != PICO_ERROR_TIMEOUT) usb_stage[usb_len++] = (uint8_t)c;
	}
	if (usb_off < usb_len) {
		size_t used = gfx_dec_feed_bytes_lane(&gfx, 0, usb_stage + usb_off, usb_len - usb_off);
		usb_off += used;
		did |= used != 0;
	}
#ifdef GFX_UART
	size_t n;
	const uint8_t *p = uart_lane_peek(&n);
	if (n) {
		size_t used = gfx_dec_feed_bytes_lane(&gfx, 1, p, n);
		if (used) { uart_lane_consume(used); did = true; }
	}
#endif
	bool sent = false;
	if (gfx.ack_flag) {
		gfx.ack_flag = 0;
		putchar_raw(GFX_ACK_BYTE); putchar_raw(gfx.ack_seq);
		sent = true;
	}
	uint16_t ps;
	while (gfx_dec_pop_pkt_ack(&gfx, &ps)) {
		uint32_t errs = gfx.errors;
#ifdef GFX_UART
		errs += (uint32_t)uart_lane_overruns();
#endif
		putchar_raw(GFX_PKT_ACK_BYTE); putchar_raw((int)(ps & 0xFF)); putchar_raw((int)(ps >> 8));
		putchar_raw((int)(errs > 255 ? 255 : errs));
		sent = true;
	}
	if (sent) stdio_flush();
	if (gfx.leave) {
		gfx.leave = 0; gfx_active = false;
#ifdef GFX_UART
		uart_lane_flush();
#endif
	}
	return did;
}
#endif

int main(void) {
	vreg_set_voltage(VREG_VSEL);
	sleep_ms(10);
	set_sys_clock_khz(DVI_TIMING.bit_clk_khz, true);   // run at the TMDS bit clock

#if defined(GFX) && defined(USE_PSRAM)
	// Must happen before stdio/USB, interrupts and core 1 exist: the PSRAM setup takes the QMI away from the flash.
	psram_bytes = psram_init();
#endif

	stdio_init_all();   // USB CDC only (see CMakeLists.txt)
	led_init();
	led_set(true);      // solid on = alive, still starting

#ifdef GFX
	for (int i = 0; i < 256; ++i) {
		uint64_t v = 0;
		for (int b = 0; b < 8; ++b) if (i & (1 << b)) v |= (uint64_t)0xFF << (8 * b);   // bit 0 = leftmost pixel
		expand_lut[i] = v;
	}
	{
		uint8_t *cache = gfx_cache_sram, *bm = NULL;
		gfx_cache_tiles = GFX_SRAM_TILES;
		gfx_bm_bytes = 0;
		if (psram_bytes >= (size_t)GFX_CACHE_TILES * GFX_TILE_BYTES + GFX_BM_BYTES) {
			cache = psram_base();                                   // tile cache in PSRAM ...
			gfx_cache_tiles = GFX_CACHE_TILES;
			bm = psram_base() + (size_t)GFX_CACHE_TILES * GFX_TILE_BYTES;   // ... and bitmap memory behind it
			gfx_bm_bytes = GFX_BM_BYTES;
		}
		gfx_dec_init(&gfx, gfx_fb, GFX_W, GFX_H, cache, gfx_cache_tiles, bm, gfx_bm_bytes, gfx_payload, gfx_raw, GFX_RAW_MAX);
#ifdef GFX_UART
		gfx_dec_add_lane(&gfx, gfx_payload1, GFX_L1_RAW + 2);
		uart_baud = uart_lane_init();
#endif
	}
#endif
	term_init(&term);
	term_puts("usbdisplay ready\n");
	char info[48];
	snprintf(info, sizeof info, "%dx%d chars, 640x480 1bpp DVI\n", TERM_COLS, TERM_ROWS);
	term_puts(info);
	term_puts("Send text to the USB serial port.\n\n");

	dvi0.timing = &DVI_TIMING;
	dvi0.ser_cfg = DVI_PIN_CONFIG;
#ifdef DVI_INVERT
	dvi0.ser_cfg.invert_diffpairs = DVI_INVERT;
#endif
	dvi0.scanline_callback = core1_scanline_callback;
	dvi_init(&dvi0, next_striped_spin_lock_num(), next_striped_spin_lock_num());

	prepare_scanline(0);

	sem_init(&dvi_start_sem, 0, 1);
	hw_set_bits(&bus_ctrl_hw->priority, BUSCTRL_BUS_PRIORITY_PROC1_BITS);
	multicore_launch_core1(core1_main);
	sem_release(&dvi_start_sem);

	// Wait (up to 1 s) for core 1 to report that DVI is running.
	for (int i = 0; i < 100 && !dvi_running; ++i) sleep_ms(10);
	bool error = !dvi_running;
	if (!error) {
		for (int i = 0; i < 3; ++i) {   // 3 quick blinks = DVI started
			led_set(false); sleep_ms(120);
			led_set(true);  sleep_ms(120);
		}
	}

	// Core 0: pump USB bytes into the terminal and drive the status LED.
	bool led_state = true;
	uint64_t last_rx_us = 0;
	while (true) {
		uint64_t now = time_us_64();
		bool want = led_pattern(now, error, stdio_usb_connected(), last_rx_us);
		if (want != led_state) {
			led_state = want;
			led_set(want);
		}

#ifdef GFX
		if (gfx_active) {                                  // binary tile-op stream (common/gfxproto.h)
			if (gfx_poll()) last_rx_us = now ? now : 1;
			else sleep_us(50);
			continue;
		}
#ifdef GFX_UART
		uart_lane_flush();                                 // text mode ignores the UART
#endif
#endif
		int c = getchar_timeout_us(0);
		if (c == PICO_ERROR_TIMEOUT) {
			sleep_us(200);
			continue;
		}
		last_rx_us = now ? now : 1;
#ifdef GFX
		if (c == GFX_ENTER_BYTE) {
			gfx_dec_reset(&gfx);
			usb_len = usb_off = 0;
#ifdef GFX_UART
			uart_lane_flush();
#endif
			gfx_active = true;
			putchar_raw(GFX_READY_BYTE);                   // the host may start using the UART link now
			stdio_flush();
			continue;
		}
#endif
		if (term_feed(&term, (uint8_t)c)) {
			// ENQ: identify (lets the host scripts find the right port)
#ifdef GFX
			printf("USBDISPLAY 1 %dx%d pins=%d,%d,%d clk=%d inv=%d gfx=%dx%dx8 cache=%d raw=%d bm=%u psram=%u", TERM_COLS, TERM_ROWS,
			       dvi0.ser_cfg.pins_tmds[0], dvi0.ser_cfg.pins_tmds[1], dvi0.ser_cfg.pins_tmds[2],
			       dvi0.ser_cfg.pins_clk, dvi0.ser_cfg.invert_diffpairs, GFX_W, GFX_H, gfx_cache_tiles, GFX_RAW_MAX,
			       (unsigned)gfx_bm_bytes, (unsigned)psram_bytes);
#ifdef GFX_UART
			printf(" uart=%u ring=%u l1raw=%d", (unsigned)uart_baud, (unsigned)GFX_UART_RING_SIZE, GFX_L1_RAW + 2);
#endif
			printf("\r\n");
#else
			printf("USBDISPLAY 1 %dx%d pins=%d,%d,%d clk=%d inv=%d\r\n", TERM_COLS, TERM_ROWS,
			       dvi0.ser_cfg.pins_tmds[0], dvi0.ser_cfg.pins_tmds[1], dvi0.ser_cfg.pins_tmds[2],
			       dvi0.ser_cfg.pins_clk, dvi0.ser_cfg.invert_diffpairs);
#endif
			fflush(stdout);
		}
	}
}
