#!/usr/bin/env python3
"""Generate lepotato/usbdisplay-tty-ascii.h: the Unicode -> printable ASCII table used by usbdisplay-tty.c.

The mapping rules live in to_ascii() of lepotato/usbdisplay-tty.py (the reference implementation);
this script flattens them into sorted ranges so the C program needs no Unicode library.
Code points that map to '?' are left out. 0 and 32..126 are handled in code.

    python3 tools/gen_tty_ascii.py
"""
import importlib.util, os, sys

here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("ref", os.path.join(here, "..", "lepotato", "usbdisplay-tty.py"))
ref = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ref)

ranges = []                                   # [lo, hi, ch]
for cp in range(0x80, 0x110000):
    ch = ref.to_ascii(cp)
    if ch == ord("?"):
        continue
    if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == ch:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp, ch])

out = ["/* Generated by tools/gen_tty_ascii.py from lepotato/usbdisplay-tty.py - do not edit. */",
       "/* Unicode code point ranges (>= 0x80) that map to a printable ASCII character; others map to '?'. */",
       f"/* {len(ranges)} ranges */",
       "static const struct { uint32_t lo, hi; uint8_t ch; } ASCII_RANGES[] = {"]
row = []
for lo, hi, ch in ranges:
    row.append(f"{{0x{lo:X},0x{hi:X},{ch}}}")
    if len(row) == 6:
        out.append("\t" + ", ".join(row) + ","); row = []
if row:
    out.append("\t" + ", ".join(row) + ",")
out.append("};")
path = os.path.join(here, "..", "lepotato", "usbdisplay-tty-ascii.h")
with open(path, "w") as f:
    f.write("\n".join(out) + "\n")
print(f"wrote {os.path.normpath(path)}: {len(ranges)} ranges")
