#!/usr/bin/env python3
"""make_font.py - turn any font into the 8x16 table the Pico firmware draws with.

Needs Pillow (pip install pillow). Example (this is how the shipped headers were made):

  python3 make_font.py /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf \\
      --size 14 --baseline 13 --name dejavu --out ../pico/font_8x16_dejavu.h --preview dejavu.png
  python3 make_font.py /usr/share/fonts/X11/misc/ter-u16n_iso-8859-1.pcf.gz \\
      --size 16 --baseline 12 --name terminus --out ../pico/font_8x16_terminus.h

Rendering is 1-bit (no anti-aliasing) with the font's own hinting, which is what
makes TrueType fonts like DejaVu Sans Mono readable at this size.

Table layout (same as PicoDVI's font_8x8.h so the scanline code stays the same):
  font[row * 95 + (ch - 32)], 16 rows, ASCII 32..126, bit 0 = leftmost pixel.

--baseline is the pixel row the text sits on (rows 0..baseline-1 are above it,
the rest is for descenders). The script warns if any glyph has ink outside the
8x16 cell, i.e. if size/baseline need adjusting.
"""
import argparse
import sys

from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 8, 16
FIRST, COUNT = 32, 95
MARGIN = 8   # extra canvas around the cell, only used to detect clipped ink


def render_glyph(font, ch, baseline, margin):
    """Return a set of (x, y) ink pixels in cell coordinates (may lie outside the cell)."""
    w, h = CELL_W + 2 * margin, CELL_H + 2 * margin
    img = Image.new("1", (w, h), 0)
    d = ImageDraw.Draw(img)
    d.fontmode = "1"                                    # no anti-aliasing, use hinting
    d.text((margin, margin + baseline), ch, font=font, fill=1, anchor="ls")
    px = img.load()
    return {(x - margin, y - margin) for y in range(h) for x in range(w) if px[x, y]}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("font", help="TTF/OTF/PCF file")
    ap.add_argument("--size", type=int, required=True, help="pixel size (ppem) to render at")
    ap.add_argument("--baseline", type=int, required=True, help="baseline row inside the 16-row cell")
    ap.add_argument("--name", required=True, help="C identifier suffix: font_8x16_<name>")
    ap.add_argument("--index", type=int, default=0, help="face index for font collections")
    ap.add_argument("--out", help="write the C header here (default: stdout)")
    ap.add_argument("--preview", help="also write a PNG preview sheet of all 95 glyphs")
    ap.add_argument("--credit", default="", help="license/credit line for the header comment")
    args = ap.parse_args()

    font = ImageFont.truetype(args.font, args.size, index=args.index,
                              layout_engine=ImageFont.Layout.BASIC)

    glyphs = {}
    clipped = []
    for code in range(FIRST, FIRST + COUNT):
        ink = render_glyph(font, chr(code), args.baseline, MARGIN)
        if ink:
            # A glyph that is <= 8 px wide but sits 1+ px off to one side (hinting
            # can do that) is nudged back into its cell instead of being clipped.
            lo, hi = min(p[0] for p in ink), max(p[0] for p in ink)
            if hi - lo + 1 <= CELL_W:
                shift = -lo if lo < 0 else (CELL_W - 1 - hi if hi > CELL_W - 1 else 0)
                if shift:
                    ink = {(x + shift, y) for x, y in ink}
        outside = [p for p in ink if not (0 <= p[0] < CELL_W and 0 <= p[1] < CELL_H)]
        if outside:
            clipped.append((chr(code), len(outside)))
        glyphs[code] = {p for p in ink if (0 <= p[0] < CELL_W and 0 <= p[1] < CELL_H)}
    for ch, n in clipped:
        print(f"warning: {ch!r} has {n} pixel(s) outside the 8x16 cell (clipped)", file=sys.stderr)

    # rows[fy][code-32] = byte, bit 0 = leftmost pixel
    rows = [[0] * COUNT for _ in range(CELL_H)]
    for code, ink in glyphs.items():
        for x, y in ink:
            rows[y][code - FIRST] |= 1 << x

    lines = []
    lines.append(f"// font_8x16_{args.name}.h - generated by tools/make_font.py, do not edit by hand.")
    lines.append(f"// Source: {args.font.split('/')[-1]} rendered 1-bit at {args.size} px, baseline row {args.baseline}.")
    if args.credit:
        lines.append(f"// {args.credit}")
    lines.append("// Layout: font[row * 95 + (ch - 32)], 16 rows, ASCII 32..126, bit 0 = leftmost pixel")
    lines.append("// (same layout as PicoDVI's font_8x8.h).")
    lines.append(f"#ifndef USBDISPLAY_FONT_8X16_{args.name.upper()}_H")
    lines.append(f"#define USBDISPLAY_FONT_8X16_{args.name.upper()}_H")
    lines.append("#include <stdint.h>")
    lines.append("#ifndef _IMG_ASSET_SECTION")
    lines.append('#define _IMG_ASSET_SECTION ".data"   /* RAM: core 1 reads it every scanline */')
    lines.append("#endif")
    lines.append(f"static const uint8_t __attribute__((aligned(4), section(_IMG_ASSET_SECTION \".font_8x16_{args.name}\")))")
    lines.append(f"font_8x16_{args.name}[{CELL_H * COUNT}] = {{")
    for fy in range(CELL_H):
        chunk = rows[fy]
        for i in range(0, COUNT, 16):
            part = ", ".join(f"0x{b:02x}" for b in chunk[i:i + 16])
            lines.append(f"\t{part},")
    lines.append("};")
    lines.append("#endif")
    text = "\n".join(lines) + "\n"
    if args.out:
        with open(args.out, "w") as f:
            f.write(text)
    else:
        sys.stdout.write(text)

    if args.preview:
        scale = 4
        cols = 16
        nrows = (COUNT + cols - 1) // cols
        sheet = Image.new("L", (cols * (CELL_W + 2) * scale, nrows * (CELL_H + 2) * scale), 40)
        px = sheet.load()
        for code in range(FIRST, FIRST + COUNT):
            i = code - FIRST
            ox = (i % cols) * (CELL_W + 2) * scale + scale
            oy = (i // cols) * (CELL_H + 2) * scale + scale
            for x in range(CELL_W):
                for y in range(CELL_H):
                    v = 255 if (rows[y][i] >> x) & 1 else 0
                    for sx in range(scale):
                        for sy in range(scale):
                            px[ox + x * scale + sx, oy + y * scale + sy] = v
        sheet.save(args.preview)


if __name__ == "__main__":
    main()
